name: KrypticRewards

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  burn_rewards:
    runs-on: ubuntu-latest
    timeout-minutes: 36
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Initial ID
        run: python rewards.py --headless --fast --accounts ${{ secrets.FIRST_ID}}
      - name: Save logs.txt as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs.txt
      - name: Remove logs.txt
        if: always()
        run: rm logs.txt
